### ISSUE TITLE
Portable Pool Plotting

### ISSUE THREAD

**Issue by ThHaubi** [MrPig91/PSChiaPlotter#149] opened 2021-07-06 16:10 UTC
PSChiaPlotter is working for normal plots but as soon as I am ticking the pool checkbox and entering either the my pool public key or the pool public key (I don't know which it the correct one to put in there) the plots fails with -1 and the log file is totally empty

**Comment by MrPig91** [comment] 2021-07-07 14:10
I will have to run a couple test to see what is happening.

**Comment by PhattyOgre** [comment] 2021-07-09 12:45
It's working fine for me. Don't use a key of any sort (pool key, farmer key, etc). Use the contract address generated when you join the pool. This should fix your issue.

**Comment by MrPig91** [comment] 2021-07-12 03:30
I have been unable to reproduce this issue. I am able to feed it my farmer key and pool contract address and it is plotting fine. Are you giving it your pool contact address when you check that box? The pool public key field should be greyed out when that box is checked since it is not used when creating portable plots. I am closing this for now unless you are able to provide more info.

**Closed by MrPig91** 2021-07-12 03:30 UTC
