### ISSUE TITLE
Powershell Plotting Hangs at 98%

### ISSUE THREAD

**Issue by Pafolo** [MrPig91/PSChiaPlotter#32] opened 2021-05-16 15:30 UTC
Ran 3 plots in parallel, each hung at 98% and never finished in the power shell but did complete the plotting and moved the files. The power shell never completed or started the next round of plots. Any idea why this would happen? The logs show everything completed fine 6 hours ago but the power shell hasn't finished or started new plots. The Chia GUI is already using the completed plots without any issue.
![psCommand](https://user-images.githubusercontent.com/70542624/118402862-68a18280-b631-11eb-9647-55c6ca588c0e.JPG)
![psHung](https://user-images.githubusercontent.com/70542624/118402873-748d4480-b631-11eb-903a-d4d839637c78.JPG)

**Comment by Pafolo** [comment] 2021-05-17 02:08
Having tested again it hung a 98% for a minute and said like progress has failed - copying. But finished that plot and then was able to start a new plot. I'm not sure if its because I used different params this time or the script just acts funky. It copy's everything and finished before 98% and when 98% is reached the process has finished as if 98% is the new 100%. Idk if the percentages are off or the script cant see when the file is being transferred?
![ps2ndTest](https://user-images.githubusercontent.com/70542624/118423510-c0b8a300-b68a-11eb-9b63-84429755bf85.JPG)

**Comment by MrPig91** [comment] 2021-05-17 13:17
Can you tell me which version of Chia you are using? I believe the copy lines of the log files got added to a later version of Chia and is not in the earlier versions.

**Comment by Pafolo** [comment] 2021-05-17 13:50
I'm using the 1.1.5 Chia GUI and 1.0.14 PSChiaPlotter

**Comment by MrPig91** [comment] 2021-05-17 19:20
Okay so am a fool because the logs files that my script file create are a tad shorter than the ones created by the GUI. So My line number was off by like 5. So it never got to 100%. What is interesting is that even it never reached 100% it should have still continued since that progress bar is only updated if the process is still running (or has not exited). I will update the line numbers though. Thank you for bringing this up.

**Comment by MrPig91** [comment] 2021-05-17 19:59
I have updated the code with the correct line number for the copy section. This should fix the hanging out 98%. Although I still feel like the process should have continue since once the chia process exits the write-progress would be reset to the new process. Keep me updated if you come across and discoveries.

**Comment by FlashTime27** [comment] 2021-05-18 10:23
I have the same problem with the new code from yesterday.
![Untitled](https://user-images.githubusercontent.com/84375800/118634619-041e2900-b7d3-11eb-983a-c612c98b234e.png)

and this is before the update.

![Untitl1ed](https://user-images.githubusercontent.com/84375800/118635468-e8ffe900-b7d3-11eb-8939-39fec5c62445.png)

**Comment by Pafolo** [comment] 2021-05-20 04:57
The other plots 1 and 3 also hung at 98% when finishing their second plots. I'm not sure why they work fine sometimes and then another time they hang.

**Comment by MrPig91** [comment] 2021-05-21 22:24
So the last 2% is the copying phase, which doesn't track the actual progress of this, and I have seen this phase take to as little as 10 minutes to as long as 1 hour depending on how filled up the SSD is or how many plots are being copied over to the farming drive. Although I don't suspect your copying time should take very long since you have your plots staggered and you it seems like you are looking at the log files and see that it finished copying. I am sorry that I can't find the root cause of this but basically the script won't continue unless the chia plotting process has exited. So I would assume that the process is not exiting which is why the script is hanging. If the plot is 100% finished and you can see that it has finished copying you could try to force end the process. If you don't see the process in task manager or by using Get-process -id "the chia process id" then there is definitely something fishy going.

I am really sorry these scripts are working as expected.

**Comment by MrPig91** [comment] 2021-06-07 16:36
Closing for now, since no further updates have been provided. Happy farming.

**Closed by MrPig91** 2021-06-07 16:36 UTC
